server:
  port: 9099
spring:
  application:
    name: nacos-dubbo-service
  profiles:
    active: dev

dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    #集群模式
    #address: nacos://127.0.0.1:8848?backup=127.0.0.1:8849,127.0.0.1:8850
  application:
    name: nacos-dubbo-provider
  scan:
    base-packages: com.zfm.service.service
  protocol:
    name: dubbo
    port: 20800
